[tool.interrogate]
ignore-module = true
ignore-init-module = true
ignore-nested-classes = true
ignore-init-method = true
ignore-magic = true
ignore-private = false
ignore-semiprivate = false
ignore-property-decorators = false
ignore-nested-functions = true
ignore-setters = false
fail-under = 95
verbose = 1

[tool.ruff.lint]
select = [
    #pycodestyle
    "E", "W",
    # isort
    "I",
    # Pyflakes
    "F",
    # pyupgrade
    "UP",
    # flake8-bugbear
    "B",
    # flake8-simplify
    "SIM"
]
ignore = ["F401",
          "UP004",
          "SIM105", "SIM210",
          "B020"]


[tool.ruff.lint.isort]
force-single-line = true
lines-between-types = 1
lines-after-imports = 2
known-first-party = ["app",
                     "config",
                     "ml",
                     "parser",
                     "utils"]
