PROJECT_PATH = r'C:\Projects\VGChartz'

DATA_PATH = PROJECT_PATH + r'\data'
FILE_RAW_PATH = DATA_PATH + r'\raw'
CHECKPOINT_PATH = DATA_PATH + r'\raw\checkpoints'
FILE_PREPROCESSED_PATH = DATA_PATH + r'\processed'

REPORTS_PATH = PROJECT_PATH + r'\reports'
TRAIN_MODELS_REPORT_PATH = REPORTS_PATH + r'\training'

TRAINED_MODELS_PATH = PROJECT_PATH + r'\models'

MODELS_PATH = PROJECT_PATH + r'\src\ml\models'
